/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.student;

/**
 *
 * @author nakul
 */
public class StudentCoop extends javax.swing.JPanel {

    /**
     * Creates new form StudentCoop
     */
    public StudentCoop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCoop = new javax.swing.JLabel();
        lblEmployer = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        txtEmployer = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        lblFeedback = new javax.swing.JLabel();
        lblEmployment = new javax.swing.JLabel();
        lblJob = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblCourses = new javax.swing.JLabel();
        lblCertification = new javax.swing.JLabel();
        rdFullTime = new javax.swing.JRadioButton();
        rdInternship = new javax.swing.JRadioButton();
        rdPartTime = new javax.swing.JRadioButton();
        rdNuWorks = new javax.swing.JRadioButton();
        rdHealth = new javax.swing.JRadioButton();
        rdAed = new javax.swing.JRadioButton();
        rdYes = new javax.swing.JRadioButton();
        rdSelf = new javax.swing.JRadioButton();
        rdIt = new javax.swing.JRadioButton();
        rdNo = new javax.swing.JRadioButton();
        rdUserExperience = new javax.swing.JRadioButton();
        rdFinance = new javax.swing.JRadioButton();
        rdMachineLearning = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        lblCoop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCoop.setText("Co-op Update");

        lblEmployer.setText("Employer:");

        lblPosition.setText("Position:");

        txtEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerActionPerformed(evt);
            }
        });

        lblFeedback.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFeedback.setText("Feedback Form");

        lblEmployment.setText("Type of Employment:");

        lblJob.setText("How did you obtain this job:");

        lblCompany.setText("Type of Company:");

        lblCourses.setText("Courses helped in securing job:");

        lblCertification.setText("Any Certification done outside curriculum:");

        rdFullTime.setText("Full-Time");

        rdInternship.setText("Internship");

        rdPartTime.setText("Part-Time");

        rdNuWorks.setText("NuWorks");

        rdHealth.setText("Health");

        rdAed.setText("AED");

        rdYes.setText("YES");

        rdSelf.setText("Self");

        rdIt.setText("IT");

        rdNo.setText("NO");

        rdUserExperience.setText("User Experience");

        rdFinance.setText("Finance");

        rdMachineLearning.setText("Machine Learning");

        btnSave.setText("Save and Continue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFeedback)
                    .addComponent(lblCoop))
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCertification)
                    .addComponent(lblCourses)
                    .addComponent(lblCompany)
                    .addComponent(lblJob)
                    .addComponent(lblEmployment))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdFullTime)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdHealth)
                                    .addComponent(rdAed)
                                    .addComponent(rdYes))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdIt)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdUserExperience)
                                            .addComponent(rdNo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdFinance)
                            .addComponent(rdInternship)
                            .addComponent(rdMachineLearning))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdNuWorks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdSelf)
                            .addComponent(rdPartTime))
                        .addGap(255, 255, 255))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPosition)
                            .addComponent(lblEmployer))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployer, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(txtPosition)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmployer, lblPosition});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCertification, lblCompany, lblCourses, lblEmployment, lblJob});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblCoop)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployer)
                    .addComponent(txtEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(lblFeedback)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployment)
                    .addComponent(rdFullTime)
                    .addComponent(rdInternship)
                    .addComponent(rdPartTime))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJob)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdNuWorks)
                        .addComponent(rdSelf)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompany)
                    .addComponent(rdHealth)
                    .addComponent(rdIt)
                    .addComponent(rdFinance))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourses)
                    .addComponent(rdAed)
                    .addComponent(rdUserExperience)
                    .addComponent(rdMachineLearning))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertification)
                    .addComponent(rdYes)
                    .addComponent(rdNo))
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCertification, lblCompany, lblCourses, lblEmployment, lblJob});

    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCertification;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblCoop;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblEmployer;
    private javax.swing.JLabel lblEmployment;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblJob;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JRadioButton rdAed;
    private javax.swing.JRadioButton rdFinance;
    private javax.swing.JRadioButton rdFullTime;
    private javax.swing.JRadioButton rdHealth;
    private javax.swing.JRadioButton rdInternship;
    private javax.swing.JRadioButton rdIt;
    private javax.swing.JRadioButton rdMachineLearning;
    private javax.swing.JRadioButton rdNo;
    private javax.swing.JRadioButton rdNuWorks;
    private javax.swing.JRadioButton rdPartTime;
    private javax.swing.JRadioButton rdSelf;
    private javax.swing.JRadioButton rdUserExperience;
    private javax.swing.JRadioButton rdYes;
    private javax.swing.JTextField txtEmployer;
    private javax.swing.JTextField txtPosition;
    // End of variables declaration//GEN-END:variables
}
